services:
  db:
    container_name: db_prod
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PORT: ${MARIADB_PORT}
    # env_file:
    #   - .env

  app:
    container_name: app_prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
