services:
  db:
    container_name: db_dev
    env_file:
      - .env.dev

  app:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - '5555:5555'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
