services:
  db:
    container_name: db_prod
    restart: unless-stopped
    env_file:
      - .env

  app:
    container_name: app_prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
