services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    user: root
    # user: '${JENKINS_USER}:${JENKINS_GROUP}'

  db:
    image: mariadb:10
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf

  app:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
