services:
  db:
    container_name: db_prod
    restart: unless-stopped
    env_file:
      - .env.prod

  app:
    container_name: app_prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
