services:
  db:
    image: mariadb:10
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf

  app:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
      - '5555:5555'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
