services:
  docker:
    image: docker:dind
    container_name: docker_prod
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins/jenkins-docker-certs:/certs/client
      - ./jenkins/jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'
      - '3000:3000'
      - '5000:5000'

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_prod
    user: root
    ports:
      - '8080:8080'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins/jenkins-data:/var/jenkins_home
      - ./jenkins/jenkins-docker-certs:/certs/client:ro
    # user: '${JENKINS_USER}:${JENKINS_GROUP}'

  ngrok:
    image: ngrok/ngrok:latest
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - jenkins

  db:
    image: mariadb:10
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - ./mariadb/mariadb-data:/var/lib/mysql
      - ./mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf

  app:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
