services:
  db:
    image: mariadb:10
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb.cnf:/etc/mysql/mariadb.cnf

  app:
    image: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${APP_PORT}:${APP_PORT}'

volumes:
  mariadb-data:
    external: true
  mariadb.cnf:
    external: true
