services:
  jenkins:
    image: jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_home

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - jenkins
# nginx:
#   image: nginx:latest
#   container_name: nginx
#   ports:
#     - '80:80'
#     - '443:443'
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   depends_on:
#     - jenkins
